[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[context.deploy-preview]
  [context.deploy-preview.headers]
    for = "/*"
    [context.deploy-preview.headers.values]
      X-Robots-Tag = "noindex"

[context.branch-deploy]
  [context.branch-deploy.headers]
    for = "/*"
    [context.branch-deploy.headers.values]
      X-Robots-Tag = "noindex"
